print("      * ", end="\n")
print("     * * ", end="\n")
print("    *   * ", end="\n")
print("   *     * ", end="\n")
print("  ***   ***", end="\n")
print("    *   *", end="\n")
print("    *   *", end="\n")
print("    *   *", end="\n")
print("    *****  ", end="\n")

print("    *\n   * *\n  *   *\n *     *\n***   ***")
print("  *   *\n  *   *\n  *****")  